---

general:
  run-every: 1h
  log:
    location: /my-log
    level: warn

cleanup:
  - gitlab: http://example.com/gitlab
    tokens:
      - my-token
      # If multiple tokens are specified, the first will be used at all times except during the deletion of key pairs,
      # where multiple tokens can be used to delete key-pairs owned by multiple users
    tenant: my-tenant

    instances:
      remove-if-older-than: 1d
      exclude:
        - my-special-instance

    key-pairs:
      remove-only-if-unused: true
      remove-if-older-than: 1d
      exclude:
        - my-special-key-pair
