language: python

python:
  - 3.6

before_install:
  - pip install codecov
  - pip install nose
  - pip install nose-exclude

install:
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt

script:
  - nosetests -v --with-coverage --cover-package=hgicommon --cover-inclusive --exclude-test-file=excluded_tests.txt

after_success:
  - codecov